// Front-End/src/app/pages/auth/account/account.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { FormBuilder } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthSession } from '@supabase/supabase-js';
import { AuthCacheService } from 'src/app/services/Cache/auth-cache.service';
import { ProfileService } from 'src/app/services/profile.service';
import { Profile, SupabaseService } from 'src/app/services/supabase.service';
@Component({
  selector: 'app-account',
  templateUrl: './account.component.html',
  styleUrls: ['./account.component.css'],
})
export class AccountComponent implements OnInit {
  loading = false;
  profile!: Profile;
  location = 'account';

  @Input() session!: AuthSession;

  updateProfileForm = this.formBuilder.group({
    username: '',
    website: '',
    avatar_url: '',
    full_name: '',
  });

  constructor(
    private readonly supabase: SupabaseService,
    private formBuilder: FormBuilder,
    private profileService: ProfileService,
    private router: Router,
    private authCache: AuthCacheService
  ) {}

  get avatarUrl() {
    return this.updateProfileForm.value.avatar_url as string;
  }
  async updateAvatar(event: string): Promise<void> {
    this.updateProfileForm.patchValue({
      avatar_url: event,
    });
    await this.updateProfile();
  }

  async ngOnInit(): Promise<void> {
    this.loading = true;
    await this.profileService.fetchAndUpdateProfile(this.session.user);
    this.profileService.currentProfile.subscribe((profile) => {
      if (profile) {
        this.profile = profile;
        const { username, website, avatar_url, full_name } = this.profile;
        this.updateProfileForm.patchValue({
          username,
          website,
          avatar_url,
          full_name,
        });
      }
      this.loading = false;
    });
  }
  
  async updateProfile(): Promise<void> {
    try {
      this.loading = true;
      const { user } = this.session;

      const username = this.updateProfileForm.value.username as string;
      const website = this.updateProfileForm.value.website as string;
      const avatar_url = this.updateProfileForm.value.avatar_url as string;
      const full_name = this.updateProfileForm.value.full_name as string;

      const updatedProfile: Profile = {
        id: user.id,
        username,
        website,
        avatar_url,
        full_name,
      };

      const { error } = await this.supabase.updateProfile(updatedProfile);
      if (error) throw error;
      this.authCache.invalidateCache();
      this.authCache.setCache(updatedProfile);

      // Update the UI with the updated profile data
      this.profile = updatedProfile;
      this.profileService.updateProfile(this.profile);
    } catch (error) {
      if (error instanceof Error) {
        alert(error.message);
      }
    } finally {
      this.loading = false;
    }
  }

  async signOut() {
    await this.supabase.signOut().then((res) => {
      if (!res.error) {
        this.authCache.invalidateCache();
        this.router.navigate(['/']);
      } else {
        console.error(res.error);
      }
    });
  }
}

<div *ngIf="!loading; else spinner" class="flex-container">
  <h1 *ngIf="profile && profile.username" class="title">
    {{ profile.username }}
  </h1>
  <form
    class="flex-container"
    [formGroup]="updateProfileForm"
    (ngSubmit)="updateProfile()"
  >
    <h3 class="title">Update your profile</h3>
    <app-avatar
      [avatarUrl]="this.avatarUrl"
      [position]="location"
      (upload)="updateAvatar($event)"
    >
    </app-avatar>

    <div class="form-item">
      <label for="email">Email</label>
      <input id="email" type="text" [value]="session.user.email" disabled />
    </div>
    <div class="form-item">
      <label for="username">Username</label>
      <input formControlName="username" id="username" type="text" />
    </div>
    <div class="form-item">
      <label for="full_name">Full Name</label>
      <input formControlName="full_name" id="full_name" type="text" />
    </div>
    <div class="form-item">
      <label for="website">Website</label>
      <input formControlName="website" id="website" type="url" />
    </div>

    <div class="form-item-row">
      <button type="submit" class="button primary block" [disabled]="loading">
        {{ loading ? "Loading ..." : "Update" }}
      </button>
      <button class="button block" (click)="signOut()">Sign Out</button>
    </div>
  </form>
</div>
<ng-template #spinner>
  <loading-spinner></loading-spinner>
</ng-template>

// WTKReactNative/UiComponents/Pages/Auth/account.tsx
import { useState, useEffect, useContext } from 'react'
import { supabase } from "../../../utils/supabase"
import { StyleSheet, View, Alert, Text } from 'react-native'
import { Button, Input } from 'react-native-elements'
import { Session } from '@supabase/supabase-js'
import tw from '../../../utils/tailwindRN'
import { CustomButton } from '../../Reusable/CustomButtom'
import Avatar from './Avatar'
import { ProfilePicContext } from '../../../utils/Context/Profile/ProfileProvider'
export interface Profile {
  id?: string;
  username: string;
  website: string;
  avatar_url: string;
  full_name: string;
  updated_at: Date;
}


export default function Account({ session }: { session: Session }) {
  const [loading, setLoading] = useState(true)
  const [username, setUsername] = useState('')
  const [website, setWebsite] = useState('')
  const [avatarUrl, setAvatarUrl] = useState('')
  const [fullName, setFullName] = useState('')

  const { setProfilePicUrl } = useContext(ProfilePicContext)

  useEffect(() => {
    if (session) getProfile()
  }, [session])

  async function getProfile() {
    try {
      setLoading(true)
      if (!session?.user) throw new Error('No user on the session!')

      const { data, error, status } = await supabase
        .from('profiles')
        .select(`username, website, avatar_url, full_name`)
        .eq('id', session?.user.id)
        .single()
      if (error && status !== 406) {
        throw error
      }

      if (data) {
        setUsername(data.username)
        setWebsite(data.website)
        setAvatarUrl(data.avatar_url)
        setFullName(data.full_name)
      }
    } catch (error) {
      if (error instanceof Error) {
        Alert.alert(error.message)
      }
    } finally {
      setLoading(false)
    }
  }

  async function updateProfile({
    username,
    website,
    avatar_url,
    full_name,
  }: {
    username: string
    website: string
    avatar_url: string
    full_name: string
  }) {
    try {
      setLoading(true)
      if (!session?.user) throw new Error('No user on the session!')

      const updates: Profile = {
        id: session?.user.id,
        username,
        website,
        avatar_url,
        full_name,
        updated_at: new Date(),
      }


      console.log('Updating profile with:', updates); // Log the data being sent

      const data = await supabase.from('profiles').upsert(updates).then((data) => {
        console.log('Supabase response:', data); // Log the response from Supabase
        if (Error) {
          throw Error
        }

      });

    } catch (error) {
      if (error instanceof Error) {
        Alert.alert(error.message)
      }
    } finally {
      setLoading(false)
    }
  }

  return (
    <View style={tw.style(`flex flex-col justify-center items-center
     bg-black text-white mx-4 p-4 rounded-md my-auto border border-cream`)}>
      <View style={tw.style(`py-2 flex justify-center items-center`)}>
        <Avatar
          size={200}
          url={avatarUrl}
          onUpload={(url: string) => {
            setAvatarUrl(url)
            setProfilePicUrl(url)
            updateProfile({ username, website, avatar_url: url, full_name: fullName })
          }}
          location='profile'
        />
      </View>
      <View style={tw.style(`self-stretch`)}>
        <Input style={tw.style(`text-white`)} label="Email" value={session?.user?.email} disabled />
      </View>
      <View style={tw.style(`self-stretch`)}>
        <Input style={tw.style(`text-white`)} label="Username" value={username || ''} onChangeText={(text) => setUsername(text)} />
      </View>
      <View style={tw.style(`self-stretch`)}>
        <Input style={tw.style(`text-white`)} label="Website" value={website || ''} onChangeText={(text) => setWebsite(text)} />
      </View>
      <View style={tw.style(`self-stretch`)}>
        <Input style={tw.style(`text-white`)} label="Full Name" value={fullName || ''} onChangeText={(text) => setFullName(text)} />
      </View>
      <View style={tw.style(`self-stretch py-4 mt-4`)}>
        <CustomButton title={loading ? 'Loading ...' : 'Update'} onPress={() => updateProfile({ username, website, avatar_url: avatarUrl, full_name: fullName })}
          txtStyle={tw`text-black`} btnStyle={tw`bg-cream`} disabled={loading} />
      </View>
      <View style={tw.style(`self-stretch`)}>
        <CustomButton title="Sign Out" onPress={() => supabase.auth.signOut()} txtStyle={tw`text-black`} btnStyle={tw`bg-cream`} />
      </View>
    </View>
  )
}
